-- 서울에 위치한 식당 목록 출력하기 (SELECT part)
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS I, REST_REVIEW AS R
WHERE I.ADDRESS LIKE '서울%'
AND I.REST_ID = R.REST_ID
GROUP BY R.REST_ID
ORDER BY 6 DESC, 4 DESC;