-- 자동차 종류 별 특정 옵션이 포함된 자동차 수 구하기 (GROUP BY part)
-- 1. LIKE 사용
SELECT CAR_TYPE, COUNT(*) AS CARS
FROM CAR_RENTAL_COMPANY_CAR
WHERE OPTIONS LIKE '%통풍시트%' OR OPTIONS LIKE '%열선시트%' OR OPTIONS LIKE '%가죽시트%'
GROUP BY 1
ORDER BY 1;

-- 2. REGEXP_LIKE 사용
-- SELECT CAR_TYPE, COUNT(*) AS CARS
-- FROM CAR_RENTAL_COMPANY_CAR
-- WHERE REGEXP_LIKE (OPTIONS, '통풍시트|열선시트|가죽시트') 
-- GROUP BY 1
-- ORDER BY 1;