-- 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기 (GROUP BY part)
SELECT CAR_ID,
CASE
    WHEN MAX('2022-10-16' BETWEEN DATE_FORMAT(START_DATE, '%Y-%m-%d') AND DATE_FORMAT(END_DATE, '%Y-%m-%d'))
    THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 1
ORDER BY 1 DESC;