-- 대여 기록이 존재하는 자동차 리스트 구하기 (String, Date part)
SELECT DISTINCT C.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단'
AND H.START_DATE LIKE '%-10-%'
ORDER BY 1 DESC;